-- Daily option flow reports generated by the Vercel cron job.

create table public.option_flow_reports (
  id uuid primary key default gen_random_uuid(),
  report_date date not null,
  source text not null default 'cboe',
  symbols text[] not null default '{}',
  status text not null default 'completed' check (status in ('completed', 'partial', 'failed')),
  scheduled_time_zone text not null default 'America/New_York',
  fetched_at timestamptz not null default now(),
  report jsonb not null default '{}'::jsonb,
  errors text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (report_date, source)
);

create index option_flow_reports_date_idx on public.option_flow_reports (report_date desc);

alter table public.option_flow_reports enable row level security;

create policy "option flow reports select authenticated" on public.option_flow_reports
  for select using (auth.role() = 'authenticated');
